const RequiemFusion = Dict(
    :name => "RequiemFusion",
    :current_members => [
        "AngelaPapi",
        "Annanana",
        "Berserkresse",
        "Black Dahlia",
        "bnv",
        "Breyn",
        "D_Mac",
        "Displace",
        "DocStrange",
        "Dom",
        "Drizzt4Ever",
        "Fisichella",
        "Foxgloves",
        "Glory",
        "Imper0s",
        "IrishWrath",
        "KARMA",
        "Kropman",
        "Lux",
        "matrixttd",
        "Mazsola",
        "Mbad",
        "Mikaeus",
        "Minimoose27",
        "MrMilanna",
        "Psykosis",
        "skinwalker",
        "The Wiza",
        "uncleb",
        "WhoTFCars"
        ],
    :past_members => [
        "Rhellik",
        "Tristanslav",
        "Fryseboksen",
        "sillien",
        "TRUNG"
        ]
    )

const BoethiasChampions = Dict(
    :name => "BoethiasChampions",
    :current_members => [
        "Alnitak",
        "Antar",
        "Aras-LT",
        "Ashen",
        "Chizzy",
        "Clam",
        "Dark",
        "Defeated",
        "Eraser",
        "Flmfx",
        "GodofWar",
        "Grakas",
        "Hellsorcerer",
        "Hollaaa",
        "Hsubox",
        "Lie_to_me",
        "loki",
        "Malachai",
        "Mantis",
        "Mellow",
        "Myname",
        "Peppe",
        "Pigbag",
        "Rukes",
        "Sagitarius",
        "Saint",
        "Sicarium",
        "Skytng",
        "Spinesnap"
    ],
    :past_members => [
        "Ilya"
    ]
)
