const RequiemFusion = Dict(
    :name => "RequiemFusion",
    :current_members => [
        "AngelaPapi",
        "Annanana",
        "Berserkresse",
        "bnv",
        "Breyn",
        "D_Mac",
        "Displace",
        "DocStrange",
        "Dom",
        "Drizzt4Ever",
        "Fisichella",
        "Foxgloves",
        "Glory",
        "Imper0s",
        "IrishWrath",
        "KARMA",
        "Kropman",
        "Lux",
        "matrixttd",
        "Mazsola",
        "Mbad",
        "Mikaeus",
        "Minimoose27",
        "MrMilanna",
        "Psykosis",
        "sillien",
        "skinwalker",
        "The Wiza",
        "TRUNG",
        "WhoTFCars"
        ],
    :past_members => [
        "Rhellik",
        "Tristanslav",
        "Fryseboksen"
        ]
    )
